---
title: "課堂練習模版"
author: "tom0410"
date: "2020-11-18"
output: output_format
params:
  id: "410973093"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
# 有多少名字可選：
names(listExample)
```
```{r}
listExample$student
listExample$學期 # 特殊命名依然要用反頓點呼叫
```

```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]]  # 小心不是反頓點喔。
listExample$學期
```

```{r}
example <- list(name = c("小明", "小花", "小新", "美美"), height = c(175, 
    166, 170, 160), weight = c(77, NA, 60, 43), birthday = lubridate::ymd(c("1998-03-11", 
    "1999-12-22", "1995-08-22", "2001-10-10")), hobby = c("美食 旅遊", "旅遊 時尚", 
    "3C 美食", "音樂 旅遊"), residence = c("Taipei", "New Taipei", "Taichung", 
    "Kaohsiung"), allowance = factor(c("0-1000", "1001-2000", "2000+", "1001-2000")), 
    bloodType = c("A", "B", "B", "O"))
```

```{r}
example$name[c(T, F, T, F)]
```

```{r}
str(example[c("name", "height")])

pick_above170 <- example$height >= 170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```

```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
```

```{r}
str(transcript100to103)
```

```{r}
# 各學屆2年級人數
table(transcript100to103$學屆)
# 各學屆2年級成績大於85年數
table(transcript100to103$學屆[pick_above85])
```

```{r}
# 只要成績大於85的
pick_above85 <- transcript100to103$成績 > 85
```

```{r}
# 各學屆2年級人數
table(transcript100to103$學屆)
# 各學屆2年級成績大於85人數
table(transcript100to103$學屆[pick_above85])
```

```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)
```

```{r}
print(example[c("name", "birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```

