---
title: "課?<a0>?練習模<e7><89><88>"
author: "tom0410"
date: "2020-10-28"
output: output_format
params:
  id: "410973093"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
vectorExample <- c("小明", "小英", "大雄")

# 有多少位置可選：
length(vectorExample)

vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- list(student = "小明", 
                    學期 = list(
                      `108-1` = list(
                        list(
                          name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))

# 有多少位置可選：
length(listExample)

listExample[[1]]
listExample[[2]]
```

```{r}
# 有多少名字可選：
names(listExample)

listExample$student
listExample$學期  # 特殊命名依然要用反頓點呼叫

listExample[["student"]]
listExample$student

listExample[["學期"]]  # 小心不是反頓點喔。
listExample$學期
```

```{r}
vectorExample
vectorExample[c(1, 3)]

# 顯示到第一層
str(listExample, max.level = 1)

listExample[c(1, 2)]
```

```{r}
vectorExample
vectorExample[c(1, 3)]
```

```{r}
# 顯示到第一層
str(listExample, max.level = 1)

listExample[c(1, 2)]
```

```{r}
vectorExample[c(1)]
vectorExample[1]
vectorExample[[1]]
```

```{r}
vectorExample
vectorExample[c(T, T, F)]  # 要，要，不要

str(listExample[c(F, T)])  # 不要，要
str(listExample[c(T, T)])  # 要，要
```

```{r}
listExample[1]
listExample[[1]]
```

```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
```

```{r}
select1 <- numVector[c(T, T, F, T, F, F, T)]
select1
select2 <- select1[c(1, 4)]
select2

# 相當於
numVector[c(T, T, F, T, F, F, T)][c(1, 4)]
```

```{r}
majorsStudent <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
namesStudent <- c("小英", "小美", "大雄", "阿華", "阿尼")
genderStudent <- c("F", "F", "M", "F", "M")
```

```{r}
majors
```

```{r}
pickEcon <- c(T,T,F,F,T)
namesStudent[pickEcon]
genderStudent[pickEcon]
```

```{r}
pickEcon <- majorsStudent
```

```{r}
whichHasEcon <- which(pickEcon) ##邏輯轉數字
```

```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
str(today,2)
str(tomorrow,2)
```

