---
title: "課?<a0>?練習模<e7><89><88>"
author: "tom0410"
date: "2020-10-14"
output: output_format
params:
  id: "410973093"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```

##loogical=boolean

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```

```{r}
typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```
##(X)"1"+"1.5" "會考!!"
```{r}
1+1.5
```

```{r}
class(1)
class(1.5)
```

```{r}
as.numeric("1")
```
##as.numeric(a)->a(記得回存!)
```{r}
a<-"1"
as.numeric(a)->a
a+4
```

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
typeof(majors10_char)
class(majors10_char)
```
##factor
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系'))
typeof(majors10_factor)
class(majors10_factor)
```

```{r}
majors4_factor
as.integer(majors4_factor) 
```

```{r}
majors4_char <- c('經濟','會計','經濟','會計')
typeof(majors4_char)
class(majors4_char)
```

```{r}
majors4_factor<-factor(c('經濟','會計','經濟','會計'))
typeof(majors4_factor)儲存方式
class(majors4_factor)顯示方式
```

```{r}
a<-factor(c("一","二","三"))
as.integer(factor(c("一","二","三")))
```

